### ISSUE TITLE
Payments

### ISSUE THREAD

**Issue by OMRKiruha** [baderouaich/tgbotxx#2]
Are the sendInvoice and answerPreCheckoutQuery functions implemented?? Is there an example of implementing subscription payment via telegram bot?

**Comment by baderouaich** [comment]
Hi @OMRKiruha,
[Payment](https://core.telegram.org/bots/api#payments) functions are not yet implemented, I will add them with examples as soon as I find some time.

**Comment by baderouaich** [comment]
I have implemented the payments API methods. 
Please refer to [PaidSubscriptionBot](https://github.com/baderouaich/tgbotxx/tree/main/examples/PaidSubscriptionBot) example for reference on how to program a subscription payment Telegram bot.
Also if you have any questions don't hesitate to open another issue.
Thank you for opening this issue and Merry Christmas to you!

**Comment by OMRKiruha** [comment]
Thank you very much for the quick response and the excellent library. 
Good luck in your endeavors. Happy New Year and Merry Christmas.
