### ISSUE TITLE
Exption: Not Found. Did you enter the correct bot token?

### ISSUE THREAD

**Issue by OMRKiruha** [baderouaich/tgbotxx#4]
Hello.
Bot can start and get updates(recieve command and messages), but cant send messages.
On send message bot catch excepton Not Found. Did you enter the correct bot token?
Can you help?

ReplyKeyboardMarkup - work correct with my token
InlineKeyboardButton - work correct with my token
EchoBot - work correct with my token

**Comment by baderouaich** [comment]
Hi @OMRKiruha,
Can you please provide more information about the arguments you pass to `api()->sendMessage(...)`? 

Usually "Not Found" error happens when your Bot token is invalid, but in your case you receive updates which means this isn't the issue.

It also happens when a Chat id or User id are invalid for example when:
- the user id changes (the user deletes their account and creates a new one)
- the chat was not initiated yet with a `/start` command so the Bot doesn't know about the user yet
- the Bot has no message sending permissions in a Chat.
 
What you can try for now to debug:
- Double check chatId or userId
- Make sure you have the necessary permissions to send messages to the specified chat

**Comment by OMRKiruha** [comment]
Here is function wrapping api()->sendMessage(...)
````
void safeSendMessage(int64_t userID, std::string_view messageText,
                         const tgbotxx::Ptr<tgbotxx::IReplyMarkup> &keyboard = nullptr) {
        using namespace std::chrono_literals;
        std::shared_ptr<tgbotxx::Message> msg{};
        size_t attempt{};
        do {
            if (attempt != 0) {
                std::cerr << getTimestamp() << "Attempt №" << attempt << " to send message to user ID " << userID
                          << std::endl;
                std::this_thread::sleep_for(2s);
            }
            try {
                msg = api()->sendMessage(userID, messageText.data(),
                                         0, "", {},
                                         false, false,
                                         true, 0,
                                         false, keyboard);
            } catch (const tgbotxx::Exception &e) {
                if (std::string(e.what()) == "Forbidden: bot was blocked by the user") {
                    return;
                }
                std::cerr << "HistoryBot: Can't send message: '" << messageText
                          << "' to user ID " << userID << " " << e.what() << std::endl;
            } catch (...) {
                std::cerr << "HistoryBot: Can't send message: '" << messageText
                          << "' to user ID " << userID << std::endl;
            }
        } while ((msg == nullptr) && (++attempt < 5));
    }
````

Here is invoke function
`std::async(std::launch::async, &HistoryBot::safeSendMessage, *this, userID, messageText, keyboard);`

**Comment by baderouaich** [comment]
Interesting, can I know what are you passing to `keyboard`, Its possible that can be the culprit

**Comment by OMRKiruha** [comment]
`nullptr` 
or something like this 
![untitled](https://github.com/baderouaich/tgbotxx/assets/35088488/2939dae3-a575-400a-acf6-8602f6b8c5f7)

**Comment by OMRKiruha** [comment]
Earlier it works.
On commit 47273a853407977c9b00d4c9dfc43c5817a3ad43 - work
On commit 4c1c1575286341bae0e33f2b68df9830e83ce570 - work
On commit 859be0cfa4c86925dea78e6eb60bedf913e9b414 - work

**Comment by OMRKiruha** [comment]
All works.
Sorry, it's my fault. 
Needed to full delete build directory.

**Comment by baderouaich** [comment]
Ah this happens sometimes! its always good to clean and rebuild the build folder. Thank you for investigating the issue step by step :+1: 
Have a good rest of day! :shamrock:
